version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./dbs/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  testdb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    volumes:
      - testdb:/var/lib/mysql
      - ./dbs/testdb/init.sql:/docker-entrypoint-initdb.d/init.sql
  e2edb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=e2edb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3308:3306'
    volumes:
      - e2edb:/var/lib/mysql
      - ./dbs/e2edb/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  e2edb:
    driver: local
  testdb:
    driver: local
  db:
    driver: local
